name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0
          components: clippy, rustfmt
          targets: wasm32-wasip1
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo lint
      - run: cargo test --lib
      - run: cargo wasm
